# Stage 1: Build the client app
FROM node:18-alpine AS client-build

WORKDIR /app

# Install dependencies
COPY client/package.json ./
RUN yarn install

# Copy the client source code
COPY client/ ./

# Build the production-ready client app
RUN yarn build
