version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network

  server: 
    build: 
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/jwt
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
    networks:
      - app-network
    
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network: