version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.prod
    volumes:
      - client-build:/client-build
    ports:
      - "80:80"
    environment:
      NODE_ENV: production

  server:
    build:
      context: .
      dockerfile: server/Dockerfile.prod
    volumes:
      - client-build:/client-build
    ports:
      - "8000:8000"
    env_file:
      - server/.env
    environment:
      NODE_ENV: production
      CLIENT_BUILD_PATH: /client-build
    depends_on:
      - redis
      - client
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  client-build:
  redis_data:
