version: "3.8"

services:
  server:
    image: "${SERVER_IMAGE}"
    ports:
      - "8000:8000"
    env_file:
      - server/.env
    environment:
      NODE_ENV: production
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  redis_data:
